#!/usr/bin/env python3
"""Vendor hooks/subagent_context.py into sibling plugins as _core.py.

Whole-file copy with a provenance header — the boring, drift-proof
choice. Each receiving plugin has a drift-guard test that regenerates
the body in memory and compares it to the committed copy, so hand-edits
to a vendored file or an un-synced upstream change fail that plugin's
test run.

Targets are listed in TARGETS. compact-manager is deliberately NOT a
target: it hand-ports a modified lib (float coercion, different
thresholds shape) and owns that copy outright.
"""
import datetime
import os
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO, "hooks", "subagent_context.py")
TARGETS = [
    os.path.join(REPO, "plugins", "cross-session-send-guard",
                 "hooks", "_core.py"),
]

HEADER = """\
# VENDORED — DO NOT EDIT. Generated by tools/sync-core.py from
# hooks/subagent_context.py @ {sha} on {date}.
# Regenerate: python3 tools/sync-core.py. Drift is enforced by the
# receiving plugin's test_vendor_sync.py.
"""


def body():
    with open(SOURCE) as fh:
        return fh.read()


def header():
    try:
        sha = subprocess.run(
            ["git", "-C", REPO, "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=10).stdout.strip() or "unknown"
    except Exception:
        sha = "unknown"
    date = datetime.date.today().isoformat()
    return HEADER.format(sha=sha, date=date)


def main():
    src = body()
    wrote = 0
    for target in TARGETS:
        if not os.path.isdir(os.path.dirname(target)):
            print(f"skip (plugin not present yet): {target}")
            continue
        with open(target, "w") as fh:
            fh.write(header() + src)
        print(f"wrote {target}")
        wrote += 1
    if not wrote:
        print("no targets written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
